import type { Metadata } from "next";
import { Manrope, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import Header2 from "@/components/layout/header-2";
import StickyCTA from "@/components/layout/sticky-cta";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                manrope.variable,
                "font-sans",
                inter.variable
            )}
        >
            <body className="min-h-full flex flex-col">
                <Header />
                <Header2 />
                {children}
                <Footer />
                <StickyCTA />
            </body>
        </html>
    );
}
